version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"        # Map container port 5000 to host port 5000
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./patients.db:/data/patients.db  # SQLite DB volume
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
